version: '3.3'
services:
  pg:
    image: postgres:10.7
    restart: always
    environment: 
      POSTGRES_DB: 'hndb'
      POSTGRES_USER: 'filter'
      POSTGRES_PASSWORD: 'sekret'
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - '5432:5432'
    expose:
      - '5432'

  hnfilter:
    image: golang:1.12
    command: ["/wait-for-it.sh", "pg:5432","--", "/bin/hnfilter-server"]
    environment:
      DB_PASSWORD: "sekret"
      DB_USER: "filter"
      DB_NAME: "hndb"
      DB_HOST: "pg"
      DB_PORT: "5432"
    volumes:
      - ./target/hnfilter-server:/bin/hnfilter-server
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - pg

